In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from scipy import stats
from scipy.io import loadmat

sns.set_style('whitegrid')

In [2]:
R = np.array([
    [1382.2, 1114.4],
    [1114.4, 1382.2]
])
r = np.array([1114.4, 591.72])

In [5]:
phi = np.linalg.inv(R) @ r

In [9]:
sigma2 = 1382.2 - phi@r

In [12]:
(sigma2 * np.linalg.inv(R))

array([[ 0.59780454, -0.48198045],
       [-0.48198045,  0.59780454]])

In [71]:
r = np.array([1382.2, 1114.4, 591.72, 96.215])
phi = np.array([r[1]/r[0]])
v = r[0]

phis = [phi]
vs = [v]
for i in range(2, 3+1):
    phi_nn = (r[i] - r[1:i][::-1] @ phi) / (r[0] - r[1:i] @ phi)
    v = v * (1-phi_nn**2)
    phi = np.concatenate([np.array(phi) - np.array(phi)[::-1] * phi_nn, np.array([phi_nn])])
    
    phis.append(phi)
    vs.append(v)

In [72]:
phis

[array([0.8062509]),
 array([ 1.31756622, -0.63418882]),
 array([ 1.36872116, -0.74046636,  0.08066201])]

In [73]:
vs

[1382.2, 826.2854291440104, 820.9093193476307]

In [70]:
# just to make sure durbin levison algo is correct
R = np.array([
    [1382.2, 1114.4, 591.72],
    [1114.4, 1382.2, 1114.4],
    [591.72, 1114.4, 1382.2]
])
r = np.array([1114.4, 591.72, 96.215])

np.linalg.inv(R) @ r

array([ 1.36872116, -0.74046636,  0.08066201])

In [81]:
0.081 - 1.96 / np.sqrt(585)

-3.6026598282862254e-05

In [77]:
(1.96/0.081)**2

585.5204999237919